spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: 123456hu
        url: jdbc:mysql://localhost:3306/LooptTalentManager
        username: hugx
    jpa:
        database-platform: org.hibernate.dialect.MySQL5DnnoDBDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show_sql: true
