spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

        properties:
            hibernate:
                format_sql: true
                show_sql: true

    H2:
        console:
            enabled: true
            path: /h2